Add pam service module for user-linked API keys
truenas/samba pull request #409
Opened 2024-09-09 16:53 UTC by anodos325

This commit adds a dedicated PAM service module for evaluating user-linked API keys per discussion in NEP-053. Each user may have one or more keys associated with themselves. Each key is hashed using pbkdf2-sha512 with a minimum of 29000 iterations.

The module only provides pam_sm_authenticate, other pam service module functions are stubbed-out.

2024-09-09 19:49 UTC, bmeagherix requested changes

2024-09-09 19:49 UTC, bmeagherix commented on nsswitch/pam_tdb.c
> +	 * If there were no digitis at all then end == iter_str
Typo: digits

2024-09-09 19:49 UTC, bmeagherix commented on nsswitch/pam_tdb.c
> +	 * generate hash based on password and salt + iterations in pam_tdb entry
Seems like the output is base64 encoded (and then munged).  If so, please add a comment to that effect.

2024-09-09 19:49 UTC, bmeagherix commented on nsswitch/pam_tdb.c
> +		pam_set_item (pamh, PAM_USER, username_ret);
From https://www.man7.org/linux/man-pages/man3/pam_set_item.3.html
> The pam_set_item function allows applications and PAM service modules to access and to update PAM information of item_type. For this a copy of the object pointed to by the item argument is created.

**If** I'm reading this correctly then we are required to `free(username_ret)` once the above call is done, to avoid a memory leak.

2024-09-12 18:02 UTC, anodos325 commented on nsswitch/pam_tdb.c
> +		pam_set_item (pamh, PAM_USER, username_ret);
username_ret is allocated via talloc_strdup() and so is automatically freed when we `TALLOC_FREE(ctx)`;

2024-09-12 19:37 UTC, bmeagherix requested changes

2024-09-12 19:37 UTC, bmeagherix commented on nsswitch/pam_tdb.c
> +	if ((data + sizeof(int64_t) + sizeof(uint8_t)) > endp) {
Should this be:
```
if ((data + sizeof(int64_t) + sizeof(uint32_t) + sizeof(uint8_t)) > endp) {
```
to also take the `entry_db_id` into account?

2024-09-12 19:37 UTC, bmeagherix commented on nsswitch/pam_tdb.c
> +	}
Huh.  I don't think this format of the password is documented back up the callstack.

Furthermore, do we know that the remote caller knows the DB ID?  Presumably they have to supply <db_id>-<pass>

2024-09-12 19:42 UTC, anodos325 commented on nsswitch/pam_tdb.c
> +	if ((data + sizeof(int64_t) + sizeof(uint8_t)) > endp) {
Yes. Good eye.

2024-09-12 19:43 UTC, anodos325 commented on nsswitch/pam_tdb.c
> +	}
Yeah, it's part of the string middleware returns when generating the API key.

2024-09-12 19:48 UTC, mgrimesix commented on nsswitch/pam_tdb.c
> +			tmp[strlen(salt_ptr) + i] = '=';
Really no need to recalculate strlen each loop

2024-09-12 20:45 UTC, bmeagherix approved these changes

2024-09-12 21:32 UTC, mgrimesix approved these changes
Nice!

2024-09-13 00:15 UTC, merged